#!/usr/bin/env python3
"""Generate an unattended CS2 + HLAE recording config from a Render Plan.

The generated file is a CS2 config executed at game launch (`+exec <name>`). It
schedules `mirv_streams record start` / `record end` at exact Demo Ticks using
`mirv_cmd`, then plays the Demo. After launch, no human input is required.

    python spike/scripts/gen_spike_cfg.py spike/render_plan.example.json
    python spike/scripts/gen_spike_cfg.py plan.json --strategy per-clip --out-dir spike/cfg

Strategies
    single-pass : one Demo playback, every Clip recorded inside it (fast, the
                  default; `mirv_cmd` stops and restarts recording per Clip).
    per-clip    : one config per Clip, each jumping near its start Tick first
                  (slow, but isolates a single Clip's failure).

Constraints enforced here
    * the output path must contain no spaces, because Clip names are set from
      inside a `mirv_cmd` argument and nested quoting there is unverified
    * Clips in single-pass mode must not overlap
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

TICKS_PER_SECOND = 64


def win_path(value: str) -> str:
    """CS2 configs want backslash paths."""
    return str(value).replace("/", "\\").rstrip("\\")


def validate(plan: dict) -> list[str]:
    problems: list[str] = []
    clips = plan.get("clips") or []
    if not plan.get("demo"):
        problems.append("plan.demo is required (Demo filename inside game/csgo, no path)")
    if not plan.get("output_dir"):
        problems.append("plan.output_dir is required")
    if " " in win_path(plan.get("output_dir", "")):
        problems.append("plan.output_dir must not contain spaces (see module docstring)")
    if not clips:
        problems.append("plan.clips must not be empty")
    for index, clip in enumerate(clips, start=1):
        for field in ("name", "start_tick", "end_tick"):
            if clip.get(field) in (None, ""):
                problems.append(f"clip {index}: missing '{field}'")
        if " " in str(clip.get("name", "")):
            problems.append(f"clip {index}: name must not contain spaces")
        if clip.get("end_tick") is not None and clip.get("start_tick") is not None:
            if int(clip["end_tick"]) <= int(clip["start_tick"]):
                problems.append(f"clip {index}: end_tick must be greater than start_tick")
    ordered = sorted(clips, key=lambda c: int(c.get("start_tick", 0)))
    for previous, current in zip(ordered, ordered[1:]):
        if int(current.get("start_tick", 0)) < int(previous.get("end_tick", 0)):
            problems.append(
                f"clips overlap: '{previous.get('name')}' ends after "
                f"'{current.get('name')}' starts"
            )
    return problems


def header(plan: dict, strategy: str, clip_count: int) -> list[str]:
    fps = plan.get("fps", 300)
    return [
        "// ---------------------------------------------------------------------------",
        "// AUTO-GENERATED by spike/scripts/gen_spike_cfg.py — do not edit by hand.",
        f"// Demo       : {plan['demo']}",
        f"// Clips      : {clip_count}",
        f"// Strategy   : {strategy}",
        f"// Tickrate   : {TICKS_PER_SECOND} ticks/second",
        "// ---------------------------------------------------------------------------",
        "",
        "// --- required before a Demo is loaded -------------------------------------",
        "engine_no_focus_sleep 0        // keep the engine ticking while unfocused",
        "snd_mute_losefocus 0           // keep Demo audio when unfocused",
        "mirv_cmd clear                 // never inherit scheduled commands",
        "",
        "// --- recording setup ------------------------------------------------------",
        "mirv_streams record screen enabled 1",
        f"mirv_streams record fps {fps}",
        f'mirv_streams record name "{win_path(plan["output_dir"])}"',
        f'mirv_streams settings edit afxDefault settings {plan.get("settings", "afxFfmpegYuv420p")}',
        f'mirv_streams record startMovieWav {1 if plan.get("record_audio", True) else 0}',
    ] + (["cl_draw_only_deathnotices 1   // minimal HUD, killfeed kept"] if plan.get("hide_hud") else []) + [""]


def single_pass(plan: dict) -> str:
    out = win_path(plan["output_dir"])
    lines = header(plan, "single-pass", len(plan["clips"]))
    lines.append("// --- scheduled Clip boundaries (mirv_cmd fires on Demo Tick) ---------------")
    for clip in sorted(plan["clips"], key=lambda c: int(c["start_tick"])):
        start, end = int(clip["start_tick"]), int(clip["end_tick"])
        lines += [
            f"// {clip['name']}: tick {start} -> {end} "
            f"({(end - start) / TICKS_PER_SECOND:.2f}s of Demo time)",
            f'mirv_cmd addAtTick {start} "mirv_streams record name {out}\\{clip["name"]}; mirv_streams record start"',
            f'mirv_cmd addAtTick {end} "mirv_streams record end; echo CLIP_DONE {clip["name"]}"',
        ]
    last_end = max(int(c["end_tick"]) for c in plan["clips"])
    lines += [
        "",
        f'mirv_cmd addAtTick {last_end + TICKS_PER_SECOND} "echo SPIKE_DONE"',
        "",
        "// --- start playback -------------------------------------------------------",
        f"playdemo {plan['demo'].removesuffix('.dem')}",
        "",
    ]
    return "\n".join(lines)


def per_clip_configs(plan: dict) -> dict[str, str]:
    pre_roll = int(plan.get("pre_roll_ticks", 128))
    configs: dict[str, str] = {}
    for clip in sorted(plan["clips"], key=lambda c: int(c["start_tick"])):
        start, end = int(clip["start_tick"]), int(clip["end_tick"])
        jump = max(start - pre_roll, 0)
        lines = header(plan, "per-clip", 1)
        lines += [
            "// --- jump near the Clip, then schedule its boundaries ---------------------",
            f'mirv_cmd addAtTick 1 "demo_gototick {jump}"',
            f'mirv_cmd addAtTick {start} "mirv_streams record name {win_path(plan["output_dir"])}\\{clip["name"]}; mirv_streams record start"',
            f'mirv_cmd addAtTick {end} "mirv_streams record end; echo CLIP_DONE {clip["name"]}"',
            f'mirv_cmd addAtTick {end + TICKS_PER_SECOND} "echo SPIKE_DONE"',
            "",
            f"playdemo {plan['demo'].removesuffix('.dem')}",
            "",
        ]
        configs[clip["name"]] = "\n".join(lines)
    return configs


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("plan", type=Path, help="Render Plan JSON")
    parser.add_argument("--strategy", choices=("single-pass", "per-clip"), default="single-pass")
    parser.add_argument("--out-dir", type=Path, default=None, help="write files here instead of stdout")
    args = parser.parse_args(argv)

    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    problems = validate(plan)
    if problems:
        for problem in problems:
            print(f"INVALID PLAN: {problem}", file=sys.stderr)
        return 2

    if args.strategy == "single-pass":
        outputs = {"spike_autoexec": single_pass(plan)}
    else:
        outputs = {f"spike_{name}": text for name, text in per_clip_configs(plan).items()}

    if args.out_dir is None:
        for name, text in outputs.items():
            if len(outputs) > 1:
                print(f"// ===== {name}.cfg =====")
            print(text)
        return 0

    args.out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in outputs.items():
        target = args.out_dir / f"{name}.cfg"
        target.write_text(text, encoding="utf-8", newline="\n")
        written.append(target)
        print(f"wrote {target}  ({len(text.splitlines())} lines)")
    print(f"\nstrategy={args.strategy}  configs={len(written)}  clips={len(plan['clips'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
